<a href="https://colab.research.google.com/github/PraphulKamabathula/DS1002-qtm3tc/blob/main/notebooks/06_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Installing & Importing Packages

`numpy` is the first Python package we will be using. External packages not built into Python usually have to be (1) installed and (2) imported.

### Installing

To install any package into your current Google Colab session, use the `!pip` command like this:
```
!pip install numpy
```
However, `numpy` is such a common package it comes pre-installed here.

### Importing
Once a package is installed into your system, it must be imported into any Python code using the `import` command:
```
import numpy
```
### Import Aliases
Python also allows import statements to declare an alias for referencing the package. It is a common practice among `numpy` users to import it as `np` like this:
```
import numpy as np
```

In [1]:
!pip install numpy

In [2]:
import numpy

In [3]:
import numpy as np

## Basic NumPy Array Functionality

In [ ]:
import numpy as np

In [19]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
z = np.ones(5)
z

array([1., 1., 1., 1., 1.])

In [20]:
z.shape

(10,)

In [22]:
z.shape

(5,)

In [9]:
z = np.linspace(2, 10, 5)         # go from 2 to 10, with 5 elements
z

array([ 2.,  4.,  6.,  8., 10.])

In [13]:
z = np.linspace(5, 20, 10)
z

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ])

In [15]:
a_list = [1,2,3,4,5,6,7]
z = np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7]])

In [16]:
b_list = [1,3,5,7,9,11,13,15,17,19,21,23]
z = np.array([b_list])
z

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

In [18]:
type(z)

numpy.ndarray

In [17]:
type(z)

numpy.ndarray

In [23]:
b_list = [[9,8,7,6,5,4,3],[1,2,3,4,5,6,7]]      # 2-dimensional array
z = np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [26]:
c_list = [[1,3,5,7,9,11],[2,4,6,8,10,12]]
v = np.array([c_list])
v

array([[[ 1,  3,  5,  7,  9, 11],
        [ 2,  4,  6,  8, 10, 12]]])

In [27]:
z.shape

(1, 2, 7)

In [28]:
v.shape

(1, 2, 6)

In [29]:
# Sort an array

x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [31]:
y = [1,42,5,63,199,3,46,2,4,63,67,54]
np.sort(y)

array([  1,   2,   3,   4,   5,  42,  46,  54,  63,  63,  67, 199])

In [32]:
z = np.array([1, 2, 3, 4, 5])

In [34]:
a = np.array([1,3,4,2,5,6,])

In [33]:
# Filter the array
z < 3

array([ True,  True, False, False, False])

In [35]:
a > 1

array([False,  True,  True,  True,  True,  True])

In [36]:
z > 3

array([False, False, False,  True,  True])

In [ ]:
# Apply a mask to an array
z[z > 3]

In [38]:
# Adding and combining arrays

a_array = np.array([1,2,3,4,5])
b_array = np.array([6,7,8,9,10])

In [39]:
a_array + b_array

array([ 7,  9, 11, 13, 15])

In [40]:
a_array + 30

array([31, 32, 33, 34, 35])

In [41]:
a_array * b_array

array([ 6, 14, 24, 36, 50])

In [42]:
a_array * 10

array([10, 20, 30, 40, 50])

## Images are Numerical Data

In [43]:
!pip install scikit-image matplotlib

In [48]:

from skimage import io

photo = io.imread('hotel.jpg')
type(photo)

FileNotFoundError: ignored

FileNotFoundError: ignored

In [ ]:
photo.shape

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(photo)

In [ ]:
plt.imshow(photo[::-1])

In [ ]:
plt.imshow(photo[:, ::-1])

In [ ]:
plt.imshow(photo[200:400, 300:500])

In [ ]:
plt.imshow(photo[::2, ::2])

In [ ]:
# Get the sin of all three channels of each pixel value

photo_sin = np.sin(photo)
photo_sin

In [ ]:
# Other built-in statistical functions

print(np.sum(photo))
print(np.prod(photo))
print(np.mean(photo))
print(np.std(photo))
print(np.var(photo))
print(np.min(photo))
print(np.max(photo))

In [ ]:
# Search every value in the array, and when a value is above 100, replace it with 255.
# Where it isn't above 100, replace with 0.

photo_masked = np.where(photo > 100, 255, 0)

In [ ]:
plt.imshow(photo_masked)

In [ ]:
# Both filter the values of the array and transpose its axes.
# Switches rows and columns.

plt.imshow(photo[:,:,0].T)